name: dummy_assignment
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  flutter_staggered_grid_view: ^0.6.2
  http: ^0.13.6
  smooth_page_indicator: ^1.1.0
  like_button: ^2.0.5
  flutter_rating_bar: ^4.0.1
  get: ^4.6.5
  shared_preferences: ^2.2.0
  sqflite: ^2.2.8
  path_provider: ^2.0.15
  google_fonts: ^4.0.3
  fluttertoast: ^8.2.1
  rename: ^2.1.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/webkul_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/webkul_logo.png
    - assets/svg_icons/
    - assets/images/
